### ISSUE TITLE
Setup project locally

### ISSUE THREAD

**Issue by omulplajei** [severus-snape-team/java-bootcamp#4]
From your local computer you should:
 - start the project
 - check the /getAllPaths endpoint
 - confirm that it lists all collections with their objects

**Comment by omulplajei** [comment]
works for me 👍

**Comment by StanciuOctav** [comment]
done

**Comment by roxanazachman01** [comment]
done

**Comment by dumabianca** [comment]
done

**Comment by addetheo** [comment]
works for me, too 😄

**Comment by GavraMihai** [comment]
done
